```{r}
rdata <- "https://github.com/ucb-stat133/stat133-fall-2017/raw/master/data/nba2017-salary-points.RData"
download.file(url = rdata, destfile = 'nba2017-salary-points.RData')
load('nba2017-salary-points.RData')
length(player)
length(rdata)
head(points)
tail(position)
summary(team)
class(player)
class(points)
class(points1)
class(points2)
class(points3)
class(position)
class(rdata)
class(salary)
class(team)
```
All objects have the same length, except for rdata
There are no missing values.
Test if something is a vector by calling is.vector(something)
Check if a given vector is of a certain data type by calling typeof(vector)

```{r}
#players in position Center, of Warriors (GSW)
player[team == "GSW" & position == "C"]
#players of both GSW (warriors) and LAL (lakers)
player[team == "GSW" & team == "GSW"]
#players in positions Shooting Guard and Point Guards, of Lakers (LAL)
player[team == "LAL" & position == "SG" & position == "PG"]
#subset Small Forwards of GSW and LAL
player[team == "LAL" & team == "GSW" & position == "SF"]
#name of the player with largest salary
player[salary == max(salary)]
#name of the player with smallest salary
player[salary == min(salary)]
#name of the player with largest number of scored points
player[points == max(points)]
#salary of the player with largest number of points
salary[player == player[points == max(points)]]
#largest salary of all Centers
max(salary[position == "C"])
#team of the player with the largest number of scored points
team[player == player[points == max(points)]]
#name of the player with the largest number of 3-pointers
player[points3 == max(points3)]

#Your Turn: create a scatterplot of points and salary for the Warriors (GSW), displaying the names of the players. Generate two scatterplots, one with raw values (original scale, and another plot with log-transformations).
gswpoints = points[team == "GSW"]
gswsalary = points[team == "GSW"]
plot(gswpoints, gswsalary)
text(gswpoints, gswsalary, labels = abbreviate(player))
plot(log(gswpoints), log(gswsalary))
text(log(gswpoints), log(gswsalary), labels = abbreviate(player))
salary_millions = salary/1000000
scored_points = points3 + points1 + points2


#positions of Warriors
factor(position[team == "GSW"])
#positions of players with salaries > 15 millions
pos = factor(position[salary_millions > 15])
#frequencies (counts) of positions with salaries > 15 millions
table(pos)
position_fac <- factor(position)
plot(scored_points, salary, col=position_fac)
plot(scored_points, salary, pch = 2, cex = 1)
```
